export enum Routes {
  HOMEPAGE = "/",
  SIGN_IN = "/signin",
  DASHBOARD = "/dashboard",
  HOST = "/host",
  GUEST = "/guest",
  DETAILS = "/details",
  REGISTER = "/register",
  REGULATIONS = "/regulations",
  PRIVACY_POLICY = "/privacy-policy",
  PARTNERS = "/partners",
  FAQ = "/faq",
  USER_PROFILE = "/user-profile",
  MANAGE_DATA = "/manage-data",
}
