name: Build and deploy test
on:
  push:
    tags:
      - "test-env/*"

env:
  reg_project_id: "ukrn-hlpr"
  deploy_project_id: "ukrn-hlpr-test"
  image_name: "sosua"
  publisher_sa_key: ${{ secrets.DEPLOYER_SA_KEY }}
  ga_id: "G-0000000000"
  fb_pixel_id: ""
  gtm_id: ""
  firebase_api_key: ${{ secrets.TEST_FIREBASE_API_KEY }}
  firebase_auth_domain: "ukrn-hlpr-test.firebaseapp.com"
  firebase_project_id: "ukrn-hlpr-test"
  firebase_storage_bucket: "ukrn-hlpr-test.appspot.com"
  firebase_messaging_sender_id: "1070051882301"
  firebase_app_id: "1:1070051882301:web:e696fe0c5ee5f427390154"
  google_maps_api_key: ${{ secrets.TEST_GOOGLE_MAPS_API_KEY }}
  domain: "https://test.uasos.org/"

jobs:
  build-docker:
    if: ${{ github.event_name == 'push' }}
    name: build-docker
    runs-on: ubuntu-latest
    environment: "test-cloud"
    steps:
      - uses: actions/checkout@v2
      - name: Set outputs
        id: vars
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
      - id: auth
        uses: "google-github-actions/auth@v0"
        with:
          credentials_json: "${{ secrets.DEPLOYER_SA_KEY }}"
      - uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: ${{env.reg_project_id}}
      - name: auth gcr.io
        run: gcloud auth configure-docker
      - name: build and push docker images
        run: docker build $BUILD_ARGS -t $IMAGE_PROJECT_ID . && docker push $IMAGE_PROJECT_ID
        env:
          IMAGE_PROJECT_ID: eu.gcr.io/${{ env.reg_project_id }}/${{ env.image_name }}:${{ steps.vars.outputs.sha_short }}
          BUILD_ARGS: >
            --build-arg NEXT_PUBLIC_GA_ID=${{ env.ga_id }}
            --build-arg NEXT_PUBLIC_FACEBOOK_PIXEL_ID=${{ env.fb_pixel_id }}
            --build-arg NEXT_PUBLIC_GTM_ID=${{ env.gtm_id }}
            --build-arg NEXT_PUBLIC_FIREBASE_API_KEY=${{ env.firebase_api_key }}
            --build-arg NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=${{ env.firebase_auth_domain }}
            --build-arg NEXT_PUBLIC_FIREBASE_PROJECT_ID=${{ env.firebase_project_id }}
            --build-arg NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=${{ env.firebase_storage_bucket }}
            --build-arg NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=${{ env.firebase_messaging_sender_id }}
            --build-arg NEXT_PUBLIC_FIREBASE_APP_ID=${{ env.firebase_app_id }}
            --build-arg NEXT_PUBLIC_GOOGLE_MAPS_API_KEY=${{ env.google_maps_api_key }}
            --build-arg NEXT_PUBLIC_DOMAIN=${{ env.domain }}
      - id: auth2
        uses: "google-github-actions/auth@v0"
        with:
          credentials_json: "${{ secrets.TEST_DEPLOYER_SA_KEY }}"
      - uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: ${{env.deploy_project_id}}
      - name: Deploy to Cloud Run Test Env
        id: deploy-service
        uses: google-github-actions/deploy-cloudrun@v0
        with:
          image: eu.gcr.io/${{ env.reg_project_id }}/${{ env.image_name }}:${{ steps.vars.outputs.sha_short }}
          service: cloudrun-srv
          region: europe-central2
          project_id: ${{env.deploy_project_id}}
