name: Build and deploy test
on:
  push:
    branches:
      - test

env:
  reg_project_id: "ukrn-hlpr"
  deploy_project_id: "ukrn-hlpr-test"
  image_name: "sosua"
  publisher_sa_key: ${{ secrets.DEPLOYER_SA_KEY }}
  ga_id: "G-0000000000"
  firebase_api_key: ${{ secrets.TEST_FIREBASE_API_KEY }}
  firebase_auth_domain: "ukrn-hlpr-dev.firebaseapp.com"
  firebase_project_id: "ukrn-hlpr-dev"
  firebase_storage_bucket: "ukrn-hlpr-dev.appspot.com"
  firebase_messaging_sender_id: "727398461288"
  firebase_app_id: "1:727398461288:web:af67d40f717ab97143b0dd"
  docker_build_args: >
    --build-arg NEXT_PUBLIC_GA_ID=${{ env.ga_id }}
    --build-arg NEXT_PUBLIC_FIREBASE_API_KEY=${{ env.firebase_api_key }}
    --build-arg NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=${{ env.firebase_auth_domain }}
    --build-arg NEXT_PUBLIC_FIREBASE_PROJECT_ID=${{ env.firebase_project_id }}
    --build-arg NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=${{ env.firebase_storage_bucket }}
    --build-arg NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=${{ env.firebase_messaging_sender_id }}
    --build-arg NEXT_PUBLIC_FIREBASE_APP_ID=${{ env.firebase_app_id }}

jobs:
  build-docker:
    if: ${{ github.event_name == 'push' }}
    name: build-docker
    runs-on: ubuntu-latest
    environment: "test-cloud"
    steps:
      - uses: actions/checkout@v2
      - name: Set outputs
        id: vars
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
      - id: auth
        uses: "google-github-actions/auth@v0"
        with:
          credentials_json: "${{ secrets.DEPLOYER_SA_KEY }}"
      - uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: ${{env.reg_project_id}}
      - name: auth gcr.io
        run: gcloud auth configure-docker
      - name: build and push docker images
        run: docker build ${{ env.docker_build_args }} -t $IMAGE_PROJECT_ID . && docker push $IMAGE_PROJECT_ID
        env:
          IMAGE_PROJECT_ID: eu.gcr.io/${{ env.reg_project_id }}/${{ env.image_name }}:${{ steps.vars.outputs.sha_short }}
      - id: auth2
        uses: "google-github-actions/auth@v0"
        with:
          credentials_json: "${{ secrets.TEST_DEPLOYER_SA_KEY }}"
      - uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: ${{env.deploy_project_id}}
      - name: Deploy to Cloud Run Test Env
        id: deploy-service
        uses: google-github-actions/deploy-cloudrun@v0
        with:
          image: eu.gcr.io/${{ env.reg_project_id }}/${{ env.image_name }}:${{ steps.vars.outputs.sha_short }}
          service: cloudrun-srv
          region: europe-central2
          project_id: ${{env.deploy_project_id}}
