name: Validate

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Run eslint
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16.x"
          cache: "yarn"
      - run: yarn
      - run: yarn precommit:lint
  tsc:
    runs-on: ubuntu-latest
    name: Run TypeScript check
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16.x"
          cache: "yarn"
      - run: yarn
      - run: yarn tsc
